import "./globals.css";
import "../styles/index.css";

import Providers from './providers';
import type { Metadata } from 'next';
import type { ReactNode } from 'react';

export const metadata: Metadata = {
  title: "ASTPP VoIP",
  description: "Generated by Inextrix with Love",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icons/astpp.jpeg" type="image/jpeg" />
      </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
